
name: gRPC

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: SQLServer UP
      run: docker run -e "ACCEPT_EULA=Y" -e "MSSQL_SA_PASSWORD=2@PassWord" -p 1433:1433 -d mcr.microsoft.com/mssql/server
    - name: Sleep for 5s
      uses: juliangruber/sleep-action@v1
      with:
       time: 10s
    - name: Setup .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: 6.0.x
    - name: Run tests
      env: 
        ConnectionStrings__SQLServer: Server=localhost,1433;Database=Shop;User=sa;Password=2@PassWord
      run: dotnet test -c Release
       
