name: gRPC

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Setup .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: 6.0.x
    - name: Restore dependencies
      run: dotnet restore
    - name: Build
      run: dotnet build --no-restore
    - name: RunSQLServer
      run: docker run -e "ACCEPT_EULA=Y" -e "MSSQL_SA_PASSWORD=Pa$$w00rd" -e "MSSQL_PID=Express" -p 1433:1433 -d mcr.microsoft.com/mssql/server:2019-latest
    - name: Sleep for 5s
      uses: juliangruber/sleep-action@v1
      with:
       time: 5s
    - name: RunAndTest
      env: 
           ConnectionStrings__SQLServer: Server=localhost:1433;Database=MyShop;User Id=sa;Password=Pa$$w00rd;
      run: |
          cd "gRPC API" && dotnet run -c Release &
          sleep 10 && dotnet test -c Release
